<?php

namespace AppBundle\Repository;

/**
 * OAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OAuthRepository extends \Doctrine\ORM\EntityRepository
{
}
